const plateData = {
    // پلاک‌های آذربایجان شرقی
    "15ب": { province: "آذربایجان شرقی", city: "تبریز" },
    "15ج": { province: "آذربایجان شرقی", city: "تبریز" },
    "15د": { province: "آذربایجان شرقی", city: "تبریز" },
    "15س": { province: "آذربایجان شرقی", city: "تبریز" },
    "15ص": { province: "آذربایجان شرقی", city: "تبریز" },
    "15ط": { province: "آذربایجان شرقی", city: "تبریز" },
    "15ق": { province: "آذربایجان شرقی", city: "تبریز" },
    "15ل": { province: "آذربایجان شرقی", city: "تبریز" },
    "15م": { province: "آذربایجان شرقی", city: "تبریز" },
    "15ن": { province: "آذربایجان شرقی", city: "تبریز" },
    "15و": { province: "آذربایجان شرقی", city: "تبریز" },
    "15ه": { province: "آذربایجان شرقی", city: "تبریز" },
    "15ی": { province: "آذربایجان شرقی", city: "تبریز" },
    
    "25ب": { province: "آذربایجان شرقی", city: "مراغه" },
    "25ج": { province: "آذربایجان شرقی", city: "مرند" },
    "25د": { province: "آذربایجان شرقی", city: "میانه" },
    "25س": { province: "آذربایجان شرقی", city: "اهر" },
    "25ص": { province: "آذربایجان شرقی", city: "سراب" },
    "25ط": { province: "آذربایجان شرقی", city: "جلفا" },
    "25ق": { province: "آذربایجان شرقی", city: "هشترود" },
    "25ل": { province: "آذربایجان شرقی", city: "بناب" },
    "25م": { province: "آذربایجان شرقی", city: "بستان‌آباد" },
    "25ن": { province: "آذربایجان شرقی", city: "شبستر" },
    "25و": { province: "آذربایجان شرقی", city: "کلیبر" },
    "25ه": { province: "آذربایجان شرقی", city: "هریس" },
    "25ی": { province: "آذربایجان شرقی", city: "آذرشهر" },
    
    "35ب": { province: "آذربایجان شرقی", city: "اسکو" },
    "35ج": { province: "آذربایجان شرقی", city: "بناب" },
    "35ج": { province: "آذربایجان شرقی", city: "ورزقان" },
    "35د": { province: "آذربایجان شرقی", city: "بناب" },
    "35د": { province: "آذربایجان شرقی", city: "عجب‌شیر" },
    "35س": { province: "آذربایجان شرقی", city: "تبریز" },
    "35س": { province: "آذربایجان شرقی", city: "چاراویماق" },
    "35ص": { province: "آذربایجان شرقی", city: "ملکان" },
    "35ط": { province: "آذربایجان شرقی", city: "مرند" },
    "35ق": { province: "آذربایجان شرقی", city: "مراغه" },
    "35ل": { province: "آذربایجان شرقی", city: "تبریز" },
    "35م": { province: "آذربایجان شرقی", city: "تبریز" },
    "35ن": { province: "آذربایجان شرقی", city: "میانه" },
    "35ه": { province: "آذربایجان شرقی", city: "تبریز" },
    "35و": { province: "آذربایجان شرقی", city: "اهر" },
    "35ی": { province: "آذربایجان شرقی", city: "تبریز" },

    // پلاک‌های آذربایجان غربی
    "17ب": { province: "آذربایجان غربی", city: "ارومیه" },
    "27ب": { province: "آذربایجان غربی", city: "خوی" },
    "27ج": { province: "آذربایجان غربی", city: "مهاباد" },
    "27د": { province: "آذربایجان غربی", city: "ماکو" },
    "27س": { province: "آذربایجان غربی", city: "سلماس" },
    "27ص": { province: "آذربایجان غربی", city: "نقده" },
    "27ط": { province: "آذربایجان غربی", city: "میاندوآب" },
    "27ق": { province: "آذربایجان غربی", city: "تکاب" },
    "27ل": { province: "آذربایجان غربی", city: "شاهین‌دژ" },
    "27م": { province: "آذربایجان غربی", city: "سردشت" },
    "27ن": { province: "آذربایجان غربی", city: "بوکان" },
    "27ه": { province: "آذربایجان غربی", city: "چالدران" },
    "27و": { province: "آذربایجان غربی", city: "پیرانشهر" },
    "27ی": { province: "آذربایجان غربی", city: "اشنویه" },
    
    // پلاک‌های اردبیل
    "91ب": { province: "اردبیل", city: "اردبیل" },
    "91ج": { province: "اردبیل", city: "اردبیل" },
    "91د": { province: "اردبیل", city: "اردبیل" },
    "91س": { province: "اردبیل", city: "پارس‌آباد" },
    "91ص": { province: "اردبیل", city: "خلخال" },
    "91ط": { province: "اردبیل", city: "گرمی" },
    "91ل": { province: "اردبیل", city: "پیله‌سوار" },
    "91ل": { province: "اردبیل", city: "مشکین‌شهر" },
    "91م": { province: "اردبیل", city: "اردبیل" },
    // پلاک‌های اصفهان
    "13ب": { province: "اصفهان", city: "اصفهان" },
    "13ج": { province: "اصفهان", city: "اصفهان" },
    "13د": { province: "اصفهان", city: "اصفهان" },
    "13س": { province: "اصفهان", city: "اصفهان" },
    "13ص": { province: "اصفهان", city: "اصفهان" },
    "13ط": { province: "اصفهان", city: "اصفهان" },
    "13ق": { province: "اصفهان", city: "اصفهان" },
    "13ل": { province: "اصفهان", city: "اصفهان" },
    "13م": { province: "اصفهان", city: "اصفهان" },
    "13ن": { province: "اصفهان", city: "اصفهان" },
    "13و": { province: "اصفهان", city: "اصفهان" },
    "13ه": { province: "اصفهان", city: "اصفهان" },
    "13ی": { province: "اصفهان", city: "اصفهان" },
    "23ب": { province: "اصفهان", city: "کاشان" },
    "23ج": { province: "اصفهان", city: "نجف‌آباد" },
    "23د": { province: "اصفهان", city: "شهرضا" },
    "23س": { province: "اصفهان", city: "خمینی‌شهر" },
    "23ص": { province: "اصفهان", city: "گلپایگان" },
    "23ط": { province: "اصفهان", city: "نطنز" },
    "23ق": { province: "اصفهان", city: "اردستان" },
    "23ل": { province: "اصفهان", city: "خوانسار" },
    "23م": { province: "اصفهان", city: "ناپین" },
    "23ن": { province: "اصفهان", city: "سمیرم" },
    "23ه": { province: "اصفهان", city: "فلاورجان" },
    "23و": { province: "اصفهان", city: "فریدون‌شهر" },
    "23ی": { province: "اصفهان", city: "لنجان" },
    "43ب": { province: "اصفهان", city: "فریدن" },
    "43ج": { province: "اصفهان", city: "مبارکه" },
    "43د": { province: "اصفهان", city: "شاهین‌شهر و میمه" },
    "43س": { province: "اصفهان", city: "آران و بیدگل" },
    "43ص": { province: "اصفهان", city: "تیران و کرون" },
    "43ط": { province: "اصفهان", city: "مبارکه" },
    "43ق": { province: "اصفهان", city: "دهاقان" },
    "43ل": { province: "اصفهان", city: "شاهین‌شهر و میمه" },
    "43م": { province: "اصفهان", city: "نجف‌آباد" },
    "43ن": { province: "اصفهان", city: "خمینی‌شهر" },
    "43ه": { province: "اصفهان", city: "لنجان" },
    "43و": { province: "اصفهان", city: "کاشان" },
    "43ی": { province: "اصفهان", city: "فلاورجان" },
    "53ب": { province: "اصفهان", city: "اصفهان" },
    "53ج": { province: "اصفهان", city: "اصفهان" },
    "53د": { province: "اصفهان", city: "اصفهان" },
    "53س": { province: "اصفهان", city: "اصفهان" },
    "53ص": { province: "اصفهان", city: "اصفهان" },
    "53ط": { province: "اصفهان", city: "شهرضا" },
    "53ق": { province: "اصفهان", city: "اصفهان" },
    "53ل": { province: "اصفهان", city: "اصفهان" },
    "53م": { province: "اصفهان", city: "شاهین‌شهر و میمه" },
    "53ن": { province: "اصفهان", city: "نجف‌آباد" },
    "53ه": { province: "اصفهان", city: "کاشان" },
    "53و": { province: "اصفهان", city: "اصفهان" },
    "53ی": { province: "اصفهان", city: "خمینی‌شهر" },
    "67ب": { province: "اصفهان", city: "اصفهان" },
    "67ج": { province: "اصفهان", city: "اصفهان" },
    "67د": { province: "اصفهان", city: "اصفهان" },
    "67س": { province: "اصفهان", city: "اصفهان" },
    "67ط": { province: "اصفهان", city: "اصفهان" },
    "67ل": { province: "اصفهان", city: "اصفهان" },
    "67م": { province: "اصفهان", city: "اصفهان" },
    "67ن": { province: "اصفهان", city: "اصفهان" },
    "67و": { province: "اصفهان", city: "اصفهان" },
    "67ق": { province: "اصفهان", city: "شاهین‌شهر و میمه" },
    "67ص": { province: "اصفهان", city: "لنجان" },
    "67ص": { province: "اصفهان", city: "فلاورجان" },
    // پلاک‌های البرز
    "21ص": { province: "البرز", city: "ساوجبلاغ" },
    "21ل": { province: "البرز", city: "کرج" },
    "21و": { province: "البرز", city: "کرج" },
    "30د": { province: "البرز", city: "کرج" },
    "30س": { province: "البرز", city: "کرج" },
    "30ل": { province: "البرز", city: "کرج" },
    "30م": { province: "البرز", city: "کرج" },
    "30ه": { province: "البرز", city: "کرج" },
    "38ب": { province: "البرز", city: "کرج" },
    "38د": { province: "البرز", city: "کرج" },
    "38س": { province: "البرز", city: "کرج" },
    "38م": { province: "البرز", city: "کرج" },
    "38ن": { province: "البرز", city: "کرج" },
    "38ه": { province: "البرز", city: "کرج" },
    "38ی": { province: "البرز", city: "کرج" },
    "68ب": { province: "البرز", city: "کرج" },
    "68ج": { province: "البرز", city: "کرج" },
    "68د": { province: "البرز", city: "کرج" },
    "68س": { province: "البرز", city: "کرج" },
    "68ص": { province: "البرز", city: "کرج" },
    "68ط": { province: "البرز", city: "کرج" },
    "68ق": { province: "البرز", city: "کرج" },
    "68ل": { province: "البرز", city: "کرج" },
    "68م": { province: "البرز", city: "کرج" },
    "68ن": { province: "البرز", city: "کرج" },
    "68و": { province: "البرز", city: "کرج" },
    "68ه": { province: "البرز", city: "کرج" },
    "68ی": { province: "البرز", city: "کرج" },
    "78ط": { province: "البرز", city: "ساوجبلاغ" },
    // پلاک‌های ایلام
    "98ب": { province: "ایلام", city: "ایلام" },
    "98ج": { province: "ایلام", city: "ایلام" },
    "98د": { province: "ایلام", city: "ایلام" },
    "98ص": { province: "ایلام", city: "مهران" },
    "98ط": { province: "ایلام", city: "بدره" },
    "98ق": { province: "ایلام", city: "دهلران" },
    "98ل": { province: "ایلام", city: "چرداول" },
    "98م": { province: "ایلام", city: "ایوان" },
    "98ن": { province: "ایلام", city: "ابدانان" },
    // پلاک‌های بوشهر
    "48ب": { province: "بوشهر", city: "بوشهر" },
    "48ج": { province: "بوشهر", city: "بوشهر" },
    "48د": { province: "بوشهر", city: "بوشهر" },
    "48س": { province: "بوشهر", city: "بوشهر" },
    "48ص": { province: "بوشهر", city: "بوشهر" },
    "58ب": { province: "بوشهر", city: "دشتستان" },
    "58ج": { province: "بوشهر", city: "گناوه" },
    "58د": { province: "بوشهر", city: "کنگان" },
    "58س": { province: "بوشهر", city: "تنگستان" },
    "58ص": { province: "بوشهر", city: "دشتی" },
    "58ط": { province: "بوشهر", city: "دیر" },
    "58ق": { province: "بوشهر", city: "دیلم" },
    "58ل": { province: "بوشهر", city: "جم" },
    "58م": { province: "بوشهر", city: "دشتستان" },
    "58ن": { province: "بوشهر", city: "کنگان" },
    // پلاک‌های تهران
    "11ب": { province: "تهران", city: "تهران بزرگ" },
    "11ج": { province: "تهران", city: "تهران بزرگ" },
    "11د": { province: "تهران", city: "تهران بزرگ" },
    "11س": { province: "تهران", city: "تهران بزرگ" },
    "11ص": { province: "تهران", city: "تهران بزرگ" },
    "11ط": { province: "تهران", city: "تهران بزرگ" },
    "11ق": { province: "تهران", city: "تهران بزرگ" },
    "11ل": { province: "تهران", city: "تهران بزرگ" },
    "11م": { province: "تهران", city: "تهران بزرگ" },
    "11ن": { province: "تهران", city: "تهران بزرگ" },
    "11و": { province: "تهران", city: "تهران بزرگ" },
    "11ه": { province: "تهران", city: "تهران بزرگ" },
    "11ی": { province: "تهران", city: "تهران بزرگ" },
    
    "22ب": { province: "تهران", city: "تهران بزرگ" },
    "22ج": { province: "تهران", city: "تهران بزرگ" },
    "22د": { province: "تهران", city: "تهران بزرگ" },
    "22س": { province: "تهران", city: "تهران بزرگ" },
    "22ص": { province: "تهران", city: "تهران بزرگ" },
    "22ط": { province: "تهران", city: "تهران بزرگ" },
    "22ق": { province: "تهران", city: "تهران بزرگ" },
    "22ل": { province: "تهران", city: "تهران بزرگ" },
    "22م": { province: "تهران", city: "تهران بزرگ" },
    "22ن": { province: "تهران", city: "تهران بزرگ" },
    "22و": { province: "تهران", city: "تهران بزرگ" },
    "22ه": { province: "تهران", city: "تهران بزرگ" },
    "22ی": { province: "تهران", city: "تهران بزرگ" },
    "33ب": { province: "تهران", city: "تهران بزرگ" },
    "33ج": { province: "تهران", city: "تهران بزرگ" },
    "33د": { province: "تهران", city: "تهران بزرگ" },
    "33س": { province: "تهران", city: "تهران بزرگ" },
    "33ص": { province: "تهران", city: "تهران بزرگ" },
    "33ط": { province: "تهران", city: "تهران بزرگ" },
    "33ق": { province: "تهران", city: "تهران بزرگ" },
    "33ل": { province: "تهران", city: "تهران بزرگ" },
    "33م": { province: "تهران", city: "تهران بزرگ" },
    "33ن": { province: "تهران", city: "تهران بزرگ" },
    "33و": { province: "تهران", city: "تهران بزرگ" },
    "33ه": { province: "تهران", city: "تهران بزرگ" },
    "33ی": { province: "تهران", city: "تهران بزرگ" },
    "44ب": { province: "تهران", city: "تهران بزرگ" },
    "44ج": { province: "تهران", city: "تهران بزرگ" },
    "44د": { province: "تهران", city: "تهران بزرگ" },
    "44س": { province: "تهران", city: "تهران بزرگ" },
    "44ص": { province: "تهران", city: "تهران بزرگ" },
    "44ط": { province: "تهران", city: "تهران بزرگ" },
    "44ق": { province: "تهران", city: "تهران بزرگ" },
    "44ل": { province: "تهران", city: "تهران بزرگ" },
    "44م": { province: "تهران", city: "تهران بزرگ" },
    "44ن": { province: "تهران", city: "تهران بزرگ" },
    "44و": { province: "تهران", city: "تهران بزرگ" },
    "44ه": { province: "تهران", city: "تهران بزرگ" },
    "44ی": { province: "تهران", city: "تهران بزرگ" },
    "55ب": { province: "تهران", city: "تهران بزرگ" },
    "55ج": { province: "تهران", city: "تهران بزرگ" },
    "55د": { province: "تهران", city: "تهران بزرگ" },
    "55س": { province: "تهران", city: "تهران بزرگ" },
    "55ص": { province: "تهران", city: "تهران بزرگ" },
    "55ط": { province: "تهران", city: "تهران بزرگ" },
    "55ق": { province: "تهران", city: "تهران بزرگ" },
    "55ل": { province: "تهران", city: "تهران بزرگ" },
    "55م": { province: "تهران", city: "تهران بزرگ" },
    "55ن": { province: "تهران", city: "تهران بزرگ" },
    "55و": { province: "تهران", city: "تهران بزرگ" },
    "55ه": { province: "تهران", city: "تهران بزرگ" },
    "55ی": { province: "تهران", city: "تهران بزرگ" },
    "66ب": { province: "تهران", city: "تهران بزرگ" },
    "66ج": { province: "تهران", city: "تهران بزرگ" },
    "66د": { province: "تهران", city: "تهران بزرگ" },
    "66س": { province: "تهران", city: "تهران بزرگ" },
    "66ص": { province: "تهران", city: "تهران بزرگ" },
    "66ط": { province: "تهران", city: "تهران بزرگ" },
    "66ق": { province: "تهران", city: "تهران بزرگ" },
    "66ل": { province: "تهران", city: "تهران بزرگ" },
    "66م": { province: "تهران", city: "تهران بزرگ" },
    "66ن": { province: "تهران", city: "تهران بزرگ" },
    "66و": { province: "تهران", city: "تهران بزرگ" },
    "66ه": { province: "تهران", city: "تهران بزرگ" },
    "66ی": { province: "تهران", city: "تهران بزرگ" },
    "77ب": { province: "تهران", city: "تهران بزرگ" },
    "77ج": { province: "تهران", city: "تهران بزرگ" },
    "77د": { province: "تهران", city: "تهران بزرگ" },
    "77س": { province: "تهران", city: "تهران بزرگ" },
    "77ص": { province: "تهران", city: "تهران بزرگ" },
    "77ط": { province: "تهران", city: "تهران بزرگ" },
    "77ق": { province: "تهران", city: "تهران بزرگ" },
    "77ل": { province: "تهران", city: "تهران بزرگ" },
    "77م": { province: "تهران", city: "تهران بزرگ" },
    "77ن": { province: "تهران", city: "تهران بزرگ" },
    "77و": { province: "تهران", city: "تهران بزرگ" },
    "77ه": { province: "تهران", city: "تهران بزرگ" },
    "77ی": { province: "تهران", city: "تهران بزرگ" },
    "88ب": { province: "تهران", city: "تهران بزرگ" },
    "88ج": { province: "تهران", city: "تهران بزرگ" },
    "88د": { province: "تهران", city: "تهران بزرگ" },
    "88س": { province: "تهران", city: "تهران بزرگ" },
    "88ص": { province: "تهران", city: "تهران بزرگ" },
    "88ط": { province: "تهران", city: "تهران بزرگ" },
    "88ق": { province: "تهران", city: "تهران بزرگ" },
    "88ل": { province: "تهران", city: "تهران بزرگ" },
    "88م": { province: "تهران", city: "تهران بزرگ" },
    "88ن": { province: "تهران", city: "تهران بزرگ" },
    "88و": { province: "تهران", city: "تهران بزرگ" },
    "88ه": { province: "تهران", city: "تهران بزرگ" },
    "88ی": { province: "تهران", city: "تهران بزرگ" },
    "99ب": { province: "تهران", city: "تهران بزرگ" },
    "99ج": { province: "تهران", city: "تهران بزرگ" },
    "99د": { province: "تهران", city: "تهران بزرگ" },
    "99س": { province: "تهران", city: "تهران بزرگ" },
    "99ص": { province: "تهران", city: "تهران بزرگ" },
    "99ط": { province: "تهران", city: "تهران بزرگ" },
    "99ق": { province: "تهران", city: "تهران بزرگ" },
    "99ل": { province: "تهران", city: "تهران بزرگ" },
    "99م": { province: "تهران", city: "تهران بزرگ" },
    "99ن": { province: "تهران", city: "تهران بزرگ" },
    "99و": { province: "تهران", city: "تهران بزرگ" },
    "99ه": { province: "تهران", city: "تهران بزرگ" },
    "99ی": { province: "تهران", city: "تهران بزرگ" },
    "10ب": { province: "تهران", city: "تهران بزرگ" },
    "10ج": { province: "تهران", city: "تهران بزرگ" },
    "10د": { province: "تهران", city: "تهران بزرگ" },
    "10س": { province: "تهران", city: "تهران بزرگ" },
    "10ص": { province: "تهران", city: "تهران بزرگ" },
    "10ط": { province: "تهران", city: "تهران بزرگ" },
    "10ق": { province: "تهران", city: "تهران بزرگ" },
    "10ل": { province: "تهران", city: "تهران بزرگ" },
    "10م": { province: "تهران", city: "تهران بزرگ" },
    "10ن": { province: "تهران", city: "تهران بزرگ" },
    "10و": { province: "تهران", city: "تهران بزرگ" },
    "10ه": { province: "تهران", city: "تهران بزرگ" },
    "10ی": { province: "تهران", city: "تهران بزرگ" },
    "20ب": { province: "تهران", city: "تهران بزرگ" },
    "20ج": { province: "تهران", city: "تهران بزرگ" },
    "20د": { province: "تهران", city: "تهران بزرگ" },
    "20س": { province: "تهران", city: "تهران بزرگ" },
    "20ص": { province: "تهران", city: "تهران بزرگ" },
    "20ط": { province: "تهران", city: "تهران بزرگ" },
    "20ق": { province: "تهران", city: "تهران بزرگ" },
    "20ل": { province: "تهران", city: "تهران بزرگ" },
    "20م": { province: "تهران", city: "تهران بزرگ" },
    "20ن": { province: "تهران", city: "تهران بزرگ" },
    "20و": { province: "تهران", city: "تهران بزرگ" },
    "20ه": { province: "تهران", city: "تهران بزرگ" },
    "20ی": { province: "تهران", city: "تهران بزرگ" },
    "40ب": { province: "تهران", city: "تهران بزرگ" },
    "40ج": { province: "تهران", city: "تهران بزرگ" },
    "40د": { province: "تهران", city: "تهران بزرگ" },
    "40س": { province: "تهران", city: "تهران بزرگ" },
    "40ص": { province: "تهران", city: "تهران بزرگ" },
    "40ط": { province: "تهران", city: "تهران بزرگ" },
    "40ق": { province: "تهران", city: "تهران بزرگ" },
    "40ل": { province: "تهران", city: "تهران بزرگ" },
    "40م": { province: "تهران", city: "تهران بزرگ" },
    "40ن": { province: "تهران", city: "تهران بزرگ" },
    "40و": { province: "تهران", city: "تهران بزرگ" },
    "40ه": { province: "تهران", city: "تهران بزرگ" },
    "40ی": { province: "تهران", city: "تهران بزرگ" },
    "50ب": { province: "تهران", city: "تهران بزرگ" },
    "50ج": { province: "تهران", city: "تهران بزرگ" },
    "50د": { province: "تهران", city: "تهران بزرگ" },
    "50س": { province: "تهران", city: "تهران بزرگ" },
    "50ص": { province: "تهران", city: "تهران بزرگ" },
    "50ط": { province: "تهران", city: "تهران بزرگ" },
    "50ق": { province: "تهران", city: "تهران بزرگ" },
    "50ل": { province: "تهران", city: "تهران بزرگ" },
    "50م": { province: "تهران", city: "تهران بزرگ" },
    "50ن": { province: "تهران", city: "تهران بزرگ" },
    "50و": { province: "تهران", city: "تهران بزرگ" },
    "50ه": { province: "تهران", city: "تهران بزرگ" },
    "50ی": { province: "تهران", city: "تهران بزرگ" },

    "21ب": { province: "تهران", city: "اسلام‌شهر" },
    "21ج": { province: "تهران", city: "رباط‌کریم" },
    "21د": { province: "تهران", city: "شهریار" },
    "21س": { province: "تهران", city: "ورامین" },
    "21ط": { province: "تهران", city: "شهریار" },
    "21ق": { province: "تهران", city: "رباط‌کریم" },
    "21ل": { province: "تهران", city: "شهریار" },
    "21م": { province: "تهران", city: "ورامین" },
    "21ن": { province: "تهران", city: "پاکدشت" },
    "21ه": { province: "تهران", city: "شهریار" },
    "21ی": { province: "تهران", city: "دماوند" },
    "30ب": { province: "تهران", city: "شهریار" },
    "30ج": { province: "تهران", city: "رباط‌کریم" },
    "30ص": { province: "تهران", city: "اسلام‌شهر" },
    "30ط": { province: "تهران", city: "ورامین" },
    "30ق": { province: "تهران", city: "شهریار" },
    "30ن": { province: "تهران", city: "شهریار" },
    "30ه": { province: "تهران", city: "دماوند" },
    "30و": { province: "تهران", city: "رباط‌کریم" },
    "38ج": { province: "تهران", city: "شهریار" },
    "38ص": { province: "تهران", city: "ورامین" },
    "38ط": { province: "تهران", city: "شهریار" },
    "38ق": { province: "تهران", city: "اسلام‌شهر" },
    "38ل": { province: "تهران", city: "رباط‌کریم" },
    "38و": { province: "تهران", city: "شهریار" },
    "78ب": { province: "تهران", city: "اسلام‌شهر" },
    "78ج": { province: "تهران", city: "رباط‌کریم" },
    "78د": { province: "تهران", city: "شهریار" },
    "78س": { province: "تهران", city: "ورامین" },
    "78ص": { province: "تهران", city: "دماوند" },
    "78ق": { province: "تهران", city: "فیروزکوه" },
    "78ل": { province: "تهران", city: "پاکدشت" },
    "78م": { province: "تهران", city: "رباط‌کریم" },
    "78ن": { province: "تهران", city: "ری" },
    "78ه": { province: "تهران", city: "شهریار" },
    "78و": { province: "تهران", city: "شمیرانات" },
    "78ی": { province: "تهران", city: "اسلام‌شهر" },
    // پلاک‌های چهارمحال و بختیاری
    "71ب": { province: "چهارمحال و بختیاری", city: "شهرکرد" },
    "71ج": { province: "چهارمحال و بختیاری", city: "شهرکرد" },
    "71د": { province: "چهارمحال و بختیاری", city: "شهرکرد" },
    "71س": { province: "چهارمحال و بختیاری", city: "شهرکرد" },
    "71ص": { province: "چهارمحال و بختیاری", city: "شهرکرد" },
    "81ب": { province: "چهارمحال و بختیاری", city: "بروجن" },
    "81ج": { province: "چهارمحال و بختیاری", city: "اردل" },
    "81د": { province: "چهارمحال و بختیاری", city: "فارسان" },
    "81س": { province: "چهارمحال و بختیاری", city: "لردگان" },
    "81ص": { province: "چهارمحال و بختیاری", city: "کوهرنگ" },
    "81ق": { province: "چهارمحال و بختیاری", city: "بروجن" },
    // پلاک‌های خراسان شمالی
    "32س": { province: "خراسان شمالی", city: "بجنورد" },
    "26ب": { province: "خراسان شمالی", city: "بجنورد" },
    "26ج": { province: "خراسان شمالی", city: "بجنورد" },
    "26د": { province: "خراسان شمالی", city: "بجنورد" },
    "26ص": { province: "خراسان شمالی", city: "شیروان" },
    "26ط": { province: "خراسان شمالی", city: "اسفراین" },
    "26ق": { province: "خراسان شمالی", city: "جاجرم و گرمه" },
    "26ل": { province: "خراسان شمالی", city: "مانه و سملقان" },
    "26م": { province: "خراسان شمالی", city: "فاروج" },
    // پلاک‌های خراسان رضوی
    "12ب": { province: "خراسان رضوی", city: "مشهد" },
    "12ج": { province: "خراسان رضوی", city: "مشهد" },
    "12د": { province: "خراسان رضوی", city: "مشهد" },
    "12س": { province: "خراسان رضوی", city: "مشهد" },
    "12ص": { province: "خراسان رضوی", city: "مشهد" },
    "12ط": { province: "خراسان رضوی", city: "مشهد" },
    "12ق": { province: "خراسان رضوی", city: "مشهد" },
    "12ل": { province: "خراسان رضوی", city: "مشهد" },
    "12م": { province: "خراسان رضوی", city: "مشهد" },
    "12ن": { province: "خراسان رضوی", city: "مشهد" },
    "12و": { province: "خراسان رضوی", city: "مشهد" },
    "12ه": { province: "خراسان رضوی", city: "مشهد" },
    "12ی": { province: "خراسان رضوی", city: "مشهد" },
    "32ب": { province: "خراسان رضوی", city: "نیشابور" },
    "32ج": { province: "خراسان رضوی", city: "سبزوار" },
    "32ص": { province: "خراسان رضوی", city: "تربت‌جام" },
    "32ط": { province: "خراسان رضوی", city: "قوچان" },
    "32ق": { province: "خراسان رضوی", city: "گناباد" },
    "32ل": { province: "خراسان رضوی", city: "تربت‌حیدریه" },
    "32م": { province: "خراسان رضوی", city: "کاشمر" },
    "32ن": { province: "خراسان رضوی", city: "تربت‌حیدریه" },
    "32ه": { province: "خراسان رضوی", city: "تایباد" },
    "32و": { province: "خراسان رضوی", city: "مشهد" },
    "32ی": { province: "خراسان رضوی", city: "نیشابور" },
    "36ب": { province: "خراسان رضوی", city: "مشهد" },
    "36ج": { province: "خراسان رضوی", city: "مشهد" },
    "36د": { province: "خراسان رضوی", city: "مشهد" },
    "36س": { province: "خراسان رضوی", city: "مشهد" },
    "36ص": { province: "خراسان رضوی", city: "مشهد" },
    "36ط": { province: "خراسان رضوی", city: "مشهد" },
    "36ق": { province: "خراسان رضوی", city: "کاشمر" },
    "36ل": { province: "خراسان رضوی", city: "نیشابور" },
    "36م": { province: "خراسان رضوی", city: "سبزوار" },
    "36ن": { province: "خراسان رضوی", city: "تربت‌حیدریه" },
    "36ه": { province: "خراسان رضوی", city: "مشهد" },
    "36و": { province: "خراسان رضوی", city: "مشهد" },
    "36ی": { province: "خراسان رضوی", city: "تربت‌جام" },
    "42ب": { province: "خراسان رضوی", city: "فریمان" },
    "42ج": { province: "خراسان رضوی", city: "مشهد" },
    "42د": { province: "خراسان رضوی", city: "سرخس" },
    "42س": { province: "خراسان رضوی", city: "درگز" },
    "42ص": { province: "خراسان رضوی", city: "خواف" },
    "42ط": { province: "خراسان رضوی", city: "چناران" },
    "42ق": { province: "خراسان رضوی", city: "مشهد" },
    "42ل": { province: "خراسان رضوی", city: "بردسکن" },
    "42م": { province: "خراسان رضوی", city: "رشتخوار" },
    "42ن": { province: "خراسان رضوی", city: "سبزوار" },
    "42ه": { province: "خراسان رضوی", city: "مشهد" },
    "42و": { province: "خراسان رضوی", city: "مشهد" },
    "42ی": { province: "خراسان رضوی", city: "تربت‌حیدریه" },
    "42ی": { province: "خراسان رضوی", city: "کلات" },
    "74ب": { province: "خراسان رضوی", city: "مشهد" },
    "74ج": { province: "خراسان رضوی", city: "قوچان" },
    "74د": { province: "خراسان رضوی", city: "مشهد" },
    "74س": { province: "خراسان رضوی", city: "مشهد" },
    "74ص": { province: "خراسان رضوی", city: "مشهد" },
    "74ط": { province: "خراسان رضوی", city: "نیشابور" },
    "74ق": { province: "خراسان رضوی", city: "مشهد" },
    "74ل": { province: "خراسان رضوی", city: "سبزوار" },
    "74م": { province: "خراسان رضوی", city: "مشهد" },
    "74ن": { province: "خراسان رضوی", city: "مشهد" },
    "74ن": { province: "خراسان رضوی", city: "گناباد" },
    "74ه": { province: "خراسان رضوی", city: "مشهد" },
    "74و": { province: "خراسان رضوی", city: "مشهد" },
    "74ی": { province: "خراسان رضوی", city: "مشهد" },
    // پلاک‌های خراسان جنوبی
    "32د": { province: "خراسان جنوبی", city: "بیرجند" },
    "52ب": { province: "خراسان جنوبی", city: "بیرجند" },
    "52ج": { province: "خراسان جنوبی", city: "بیرجند" },
    "52د": { province: "خراسان جنوبی", city: "بیرجند" },
    "52ص": { province: "خراسان جنوبی", city: "قاپنات" },
    "52ط": { province: "خراسان جنوبی", city: "فردوس" },
    "52ق": { province: "خراسان جنوبی", city: "نهبندان" },
    "52ل": { province: "خراسان جنوبی", city: "سربیشه" },
    "64ق": { province: "خراسان جنوبی", city: "طبس" },
    // پلاک‌های خوزستان
    "14ب": { province: "خوزستان", city: "اهواز" },
    "14ج": { province: "خوزستان", city: "اهواز" },
    "14د": { province: "خوزستان", city: "اهواز" },
    "14س": { province: "خوزستان", city: "اهواز" },
    "14ص": { province: "خوزستان", city: "اهواز" },
    "14ط": { province: "خوزستان", city: "اهواز" },
    "14ق": { province: "خوزستان", city: "اهواز" },
    "14ل": { province: "خوزستان", city: "اهواز" },
    "14م": { province: "خوزستان", city: "اهواز" },
    "14ن": { province: "خوزستان", city: "اهواز" },
    "14و": { province: "خوزستان", city: "اهواز" },
    "14ه": { province: "خوزستان", city: "اهواز" },
    "14ی": { province: "خوزستان", city: "اهواز" },
    "24ب": { province: "خوزستان", city: "آبادان" },
    "24ج": { province: "خوزستان", city: "خرمشهر" },
    "24د": { province: "خوزستان", city: "دزفول" },
    "24س": { province: "خوزستان", city: "بهبهان" },
    "24ص": { province: "خوزستان", city: "مسجد سلیمان" },
    "24ط": { province: "خوزستان", city: "ماهشهر" },
    "24ق": { province: "خوزستان", city: "آبادان" },
    "24ق": { province: "خوزستان", city: "دشت آزادگان" },
    "24ل": { province: "خوزستان", city: "رامهرمز" },
    "24م": { province: "خوزستان", city: "اندیمشک" },
    "24ن": { province: "خوزستان", city: "شوشتر" },
    "24ه": { province: "خوزستان", city: "ماهشهر" },
    "24ه": { province: "خوزستان", city: "شادگان" },
    "24و": { province: "خوزستان", city: "شوش" },
    "24ی": { province: "خوزستان", city: "ایذه" },
    "34ب": { province: "خوزستان", city: "باغملک" },
    "34ب": { province: "خوزستان", city: "شوش" },
    "34ج": { province: "خوزستان", city: "امیدیه" },
    "34د": { province: "خوزستان", city: "خرمشهر" },
    "34د": { province: "خوزستان", city: "هندیجان" },
    "34س": { province: "خوزستان", city: "اندیمشک" },
    "34س": { province: "خوزستان", city: "لالی" },
    "34ص": { province: "خوزستان", city: "دزفول" },
    "34ط": { province: "خوزستان", city: "ماهشهر" },
    "34ق": { province: "خوزستان", city: "آبادان" },
    "34ن": { province: "خوزستان", city: "بهبهان" },
    "34ه": { province: "خوزستان", city: "شوشتر" },
    "34و": { province: "خوزستان", city: "دزفول" },
    "34ی": { province: "خوزستان", city: "اهواز" },
    // پلاک‌های زنجان
    "87ب": { province: "زنجان", city: "زنجان" },
    "87د": { province: "زنجان", city: "زنجان" },
    "87ج": { province: "زنجان", city: "زنجان" },
    "87س": { province: "زنجان", city: "زنجان" },
    "87ص": { province: "زنجان", city: "زنجان" },
    "87ط": { province: "زنجان", city: "زنجان" },
    "97ب": { province: "زنجان", city: "ابهر" },
    "97ج": { province: "زنجان", city: "خدابنده" },
    "97د": { province: "زنجان", city: "خرم‌دره" },
    "97س": { province: "زنجان", city: "ایجرود" },
    "97ص": { province: "زنجان", city: "طارم" },
    "97ط": { province: "زنجان", city: "ماه‌نشان" },
    "97ق": { province: "زنجان", city: "ابهر" },
    // پلاک‌های سمنان
    "86ب": { province: "سمنان", city: "سمنان" },
    "86د": { province: "سمنان", city: "سمنان" },
    "86ج": { province: "سمنان", city: "سمنان" },
    "96ب": { province: "سمنان", city: "دامغان" },
    "96ج": { province: "سمنان", city: "شاهرود" },
    "96د": { province: "سمنان", city: "گرمسار" },
    "96س": { province: "سمنان", city: "مهدی‌شهر" },
    "96ص": { province: "سمنان", city: "شاهرود" },
    "96ط": { province: "سمنان", city: "شاهرود" },
    // پلاک‌های سیستان و بلوچستان
    "85ب": { province: "سیستان و بلوچستان", city: "زاهدان" },
    "85د": { province: "سیستان و بلوچستان", city: "زاهدان" },
    "85ج": { province: "سیستان و بلوچستان", city: "زاهدان" },
    "85س": { province: "سیستان و بلوچستان", city: "زاهدان" },
    "85ص": { province: "سیستان و بلوچستان", city: "زاهدان" },
    "85ط": { province: "سیستان و بلوچستان", city: "زاهدان" },
    "95ب": { province: "سیستان و بلوچستان", city: "زابل" },
    "95ج": { province: "سیستان و بلوچستان", city: "ایرانشهر" },
    "95د": { province: "سیستان و بلوچستان", city: "خاش" },
    "95س": { province: "سیستان و بلوچستان", city: "سراوان" },
    "95ص": { province: "سیستان و بلوچستان", city: "نیکشهر" },
    "95ط": { province: "سیستان و بلوچستان", city: "سرباز" },
    "95ق": { province: "سیستان و بلوچستان", city: "چابهار" },
    "95ل": { province: "سیستان و بلوچستان", city: "زابل" },
    "95م": { province: "سیستان و بلوچستان", city: "ایرانشهر" },
    "95ن": { province: "سیستان و بلوچستان", city: "سراوان" },
    "95و": { province: "سیستان و بلوچستان", city: "زابل" },
    // پلاک‌های فارس
    "63ب": { province: "فارس", city: "شیراز" },
    "63ج": { province: "فارس", city: "شیراز" },
    "63د": { province: "فارس", city: "شیراز" },
    "63س": { province: "فارس", city: "شیراز" },
    "63ص": { province: "فارس", city: "شیراز" },
    "63ط": { province: "فارس", city: "شیراز" },
    "63ق": { province: "فارس", city: "شیراز" },
    "63ل": { province: "فارس", city: "شیراز" },
    "63م": { province: "فارس", city: "شیراز" },
    "63ن": { province: "فارس", city: "شیراز" },
    "63و": { province: "فارس", city: "شیراز" },
    "63ه": { province: "فارس", city: "شیراز" },
    "63ی": { province: "فارس", city: "شیراز" },
    "73ب": { province: "فارس", city: "جهرم" },
    "73ج": { province: "فارس", city: "لارستان" },
    "73د": { province: "فارس", city: "داراب" },
    "73س": { province: "فارس", city: "فسا" },
    "73ص": { province: "فارس", city: "کازرون" },
    "73ط": { province: "فارس", city: "فیروزآباد" },
    "73ق": { province: "فارس", city: "آباده" },
    "73ل": { province: "فارس", city: "مرودشت" },
    "73م": { province: "فارس", city: "لامرد" },
    "73ن": { province: "فارس", city: "نی‌ریز" },
    "73ه": { province: "فارس", city: "اقلید" },
    "73و": { province: "فارس", city: "استهبان" },
    "73ی": { province: "فارس", city: "سپیدان" },
    "73ی": { province: "فارس", city: "ممسنی" },

    "83ب": { province: "فارس", city: "ممسنی" },
    "83ج": { province: "فارس", city: "شیراز، کازرون، مرودشت، زرین‌دشت، فیروز آباد" },
    "83د": { province: "فارس", city: "قیرکازین" },
    "83س": { province: "فارس", city: "داراب، مهر، فیروزآباد" },
    "83ص": { province: "فارس", city: "شیراز، کازرون، مرودشت، ارسنجان" },
    "83ط": { province: "فارس", city: "شیراز، کازرون، مرودشت، خرمبید، فیروزآباد" },
    "83ق": { province: "فارس", city: "آباده، بوانات" },
    "83ل": { province: "فارس", city: "فراشبند" },
    "83م": { province: "فارس", city: "لارستان" },
    "83ن": { province: "فارس", city: "کازرون" },
    "83ه": { province: "فارس", city: "جهرم" },
    "83و": { province: "فارس", city: "مرودشت" },
    "83ی": { province: "فارس", city: "فسا" },

    "93ب": { province: "فارس", city: "شیراز" },
    "93ج": { province: "فارس", city: "شیراز" },
    "93د": { province: "فارس", city: "شیراز" },
    "93س": { province: "فارس", city: "شیراز" },
    "93ص": { province: "فارس", city: "شیراز" },
    "93ط": { province: "فارس", city: "شیراز" },
    "93ق": { province: "فارس", city: "شیراز" },
    "93ل": { province: "فارس", city: "لارستان" },
    "93م": { province: "فارس", city: "شیراز" },
    "93ن": { province: "فارس", city: "شیراز" },
    "93و": { province: "فارس", city: "شیراز، کازرون، مرودشت، فیروزآباد" },
    "93ی": { province: "فارس", city: "شیراز، کازرون" }
};
const specialLettersMessages = {
    "الف": "پلاک خودروهای دولتی",
    "پ": "پلاک خودروهای پلیس (ناجا)",
    "ت": "پلاک تاکسی‌ها",
    "ث": "پلاک خودروهای سپاه پاسداران",
    "ز": "پلاک وزارت دفاع و پشتیبانی نیروهای مسلح",
    "ژ": "پلاک ویژه معلولین و جانبازان",
    "ش": "پلاک خودروهای ارتش",
    "ع": "پلاک خودروهای عمومی",
    "ف": "پلاک ستاد کل نیروهای مسلح",
    "ک": "پلاک ویژه خودروهای کشاورزی",
    "گ": "پلاک گذر موقت",
    "D": "پلاک سیاسی",
    "S": "پلاک سرویس سیاسی",
};

const numberInput = document.getElementById("numberInput");
const letterInput = document.getElementById("letterInput");
const resultAlert = document.getElementById("resultAlert");
const resultText = document.getElementById("resultText");

function validateNumber(input) {
    input.value = input.value.replace(/\D/g, ''); 
    if (input.value.length > 2) {
        input.value = input.value.slice(0, 2); 
    }
    checkPlate();
}

function checkPlate() {
    const number = numberInput.value.trim();
    const letter = letterInput.value.trim();

    if (number.length === 2 && letter) {
        const plateKey = number + letter;
        const result = plateData[plateKey];

        if (specialLettersMessages[letter]) {
            resultText.textContent = specialLettersMessages[letter];
            resultAlert.classList.remove('alert-danger');
            resultAlert.classList.remove('alert-success');
            resultAlert.classList.add('alert-warning'); 
            resultAlert.classList.remove('d-none');
        } else if (result) {
            resultText.textContent = `شهر: ${result.city} | استان: ${result.province}`;
            resultAlert.classList.remove('alert-danger');
            resultAlert.classList.remove('alert-warning');
            resultAlert.classList.add('alert-success');
        } else {
            resultText.textContent = "پلاک وارد شده معتبر نیست!";
            resultAlert.classList.remove('alert-success');
            resultAlert.classList.remove('alert-warning');
            resultAlert.classList.add('alert-danger');
        }
        resultAlert.classList.remove('d-none');
    } else {
        resultAlert.classList.add('d-none');
    }
}

letterInput.addEventListener("change", checkPlate);

function searchPlates() {
    const query = searchInput.value.trim().toLowerCase();
    resultsTableBody.innerHTML = "";

    if (query) {
        const results = Object.entries(plateData).filter(([plate, data]) => {
            return data.province.toLowerCase().includes(query) || data.city.toLowerCase().includes(query);
        });

        if (results.length > 0) {
            results.forEach(([plate, data]) => {
                const row = document.createElement("tr");
                row.innerHTML = `
                    <td>${plate}</td>
                    <td>${data.province}</td>
                    <td>${data.city}</td>
                `;
                resultsTableBody.appendChild(row);
            });
        } else {
            resultsTableBody.innerHTML = `<tr><td colspan="3" class="text-center">نتیجه‌ای یافت نشد!</td></tr>`;
        }
    } else {
        resultsTableBody.innerHTML = `<tr><td colspan="3" class="text-center">لطفاً نام استان یا شهر را وارد کنید.</td></tr>`;
    }
}


searchPanelBtn.addEventListener("click", () => {
    mainPanel.classList.add("d-none");
    searchPanel.classList.remove("d-none");
});

backToMainBtn.addEventListener("click", () => {
    searchPanel.classList.add("d-none");
    mainPanel.classList.remove("d-none");
});

searchBtn.addEventListener("click", searchPlates);
letterInput.addEventListener("change", checkPlate);

